##  다차원을 나타내는 순서
          행   열   층 ...... in R
     층   행   열             in python

In [6]:
import numpy as np

In [10]:
a4 = np.array([[1,2],[3,4]])
a5 = np.array([10,20,30,40]).reshape(2,2)
a5

array([[10, 20],
       [30, 40]])

In [5]:
a6 = np.array([10,20])
a7 = np.array([10,20,30])

In [7]:
a4 + 1   # 스칼라 연산 가능

array([[2, 3],
       [4, 5]])

In [11]:
a4 + a5   # 서로 같은 크기를 갖는 배열끼리 연산 가능

array([[11, 22],
       [33, 44]])

In [12]:
a4 + a6   # 서로 다른 크기의 배열도 연산 가능 

array([[11, 22],
       [13, 24]])

# Broadcast : 배열의 반복 연산
## 배열의 크기가 다를 때 더 작은 쪽을 큰 쪽에 반복해 준다. 반복을 이끌어 내기 위한 일치하는 숫자가 필요함
## 배열의 사이즈가 2x4 면 2 또는 4 크기의배열이 있어야 반복할 수 있다

- 양쪽 배열에 크기를 나타내는 숫자에 동일한것이 존재해야함
- 작은쪽 배열의 크기를 나타내는 나머지 숫자는 반드시 1이어야함
- 양 배열의 같은 크기를 나타내는 숫자는 각 배열의 같은 위치에 있어야함


## 색인

In [14]:
L1 = [[1,2,3],[4,5,6],[7,8,9]]
arr1 = np.array(L1)
arr2 = np.arange(1,25).reshape(2,3,4)

arr2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### 리스트에서

In [15]:
L1[1,1]   # 불가능

TypeError: list indices must be integers or slices, not tuple

In [16]:
L1[1][1]   # 가능 

5

### 배열에서

In [20]:
arr1[[0,2],:]  # 리스트를 색인값으로 전달 가능

array([[1, 2, 3],
       [7, 8, 9]])

In [21]:
arr1[1:3,:]    # 슬라이스 객체를 색인값으로 전달 가능

# ex) arr1[1:3]  arr1[1 ~ (n-1)] 까지 슬라이스

array([[4, 5, 6],
       [7, 8, 9]])

In [19]:
arr1[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [23]:
arr1[[1,2],[1,2]]   # 불가능 p(1,1) , p(2,2) 인 점으로 해석한다. 


array([5, 9])

### 리스트는 모두 리스트값으로 주면 안된다.

In [26]:
arr1[[1,2],1:3]   # 가능. 한쪽은 리스트  한쪽은 슬라이스면 가능하다.

array([[5, 6],
       [8, 9]])

In [27]:
arr1[np.ix_([1,2],[1,2])]   # 가능

array([[5, 6],
       [8, 9]])

In [28]:
arr1[[1,2],:][:,[1,2]]   # 동시에 쓰면 충돌생길수 있으니 각각 색인

array([[5, 6],
       [8, 9]])

In [29]:
#) 예제 ) arr2 에서 
arr2 = np.arange(1,21).reshape(5,4)

#1 ) 10,11,14,15,18,19 출력

In [38]:
arr2[[2,3,4],:][:,[1,2]]

array([[10, 11],
       [14, 15],
       [18, 19]])

In [40]:
arr2[np.ix_([2,3,4],[1,2])]

array([[10, 11],
       [14, 15],
       [18, 19]])

In [41]:
arr2[2:5,1:3]

array([[10, 11],
       [14, 15],
       [18, 19]])

In [42]:
# 2) 6,7,8출력

In [46]:
arr2[1,1:4]

array([6, 7, 8])

In [48]:
arr2[1,[1,2,3]]

array([6, 7, 8])

In [51]:
arr3 = np.arange(2,51,2).reshape(5,5)
arr3

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [53]:
# [[24,26],
# [34,36]] 출력


In [54]:
arr3[[2,3],1:3]

array([[24, 26],
       [34, 36]])

In [55]:
arr3[np.ix_([2,3],[1,2])]

array([[24, 26],
       [34, 36]])